language: scala
sudo: false
jdk: openjdk7
scala:
- 2.10.6
- 2.11.11
matrix:
  include:
  - jdk: oraclejdk8
    scala: 2.12.2
addons:
  apt:
    packages:
    - oracle-java8-installer
script:
- sbt ";set g8Properties in g8 in Test ~= { _ + (\"scala_version\" -> \"$TRAVIS_SCALA_VERSION\")}; g8Test"
